apiVersion: v1
kind: Service
metadata:
  name: salarypredictiondjango
  labels:
    app: salarypredictiondjango
spec:
  type: NodePort
  selector:
    app: salarypredictiondjango
  ports:
    - port: 8000
      targetPort: 8000